CREATE TABLE COUNTRIES (	
    	"ID" NUMBER(18,0) NOT NULL ENABLE, 
    	"COD" NUMBER(4,0) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"RAIS" VARCHAR2(10 BYTE), 
	"CAGED" VARCHAR2(10 BYTE), 
	"NATIONALITY" NUMBER(2,0)
);
   
CREATE UNIQUE INDEX "COUNTRIES_PK" ON "COUNTRIES" ("ID");
CREATE INDEX "COUNTRIES_NATIONALITY_IDX" ON "COUNTRIES" ("NATIONALITY"); 

ALTER TABLE "COUNTRIES" ADD CONSTRAINT "COUNTRIES_PK" PRIMARY KEY ("ID") USING INDEX "COUNTRIES_PK"  ENABLE;
ALTER TABLE "COUNTRIES" ADD CONSTRAINT "COUNTRIES_NATIONALITY_FK" FOREIGN KEY ("NATIONALITY") REFERENCES "NATIONALITY" ("ID") ENABLE;

COMMENT ON COLUMN "COUNTRIES"."ID" IS 'ID universal';
COMMENT ON COLUMN "COUNTRIES"."COD" IS 'Cod Pais de Origem';
COMMENT ON COLUMN "COUNTRIES"."DESCRIPTION" IS 'Nome do pais';
COMMENT ON COLUMN "COUNTRIES"."RAIS" IS 'Codigo do Pais de Origem';
COMMENT ON COLUMN "COUNTRIES"."CAGED" IS 'Codigo conforme manual do CAGED';
COMMENT ON COLUMN "COUNTRIES"."NATIONALITY" IS 'Codigo da Nacionalidade';
COMMENT ON TABLE  "COUNTRIES"  IS 'Unidades da Federação';
