CREATE TABLE COUNTRIES (	
    "ID" NUMBER(18,0) NOT NULL ENABLE, 
    "COD" NUMBER(4,0) UNIQUE NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(60 BYTE) UNIQUE NOT NULL ENABLE, 
	"RAIS" VARCHAR2(10 BYTE), 
	"CAGED" VARCHAR2(10 BYTE), 
	"NATIONALITY" NUMBER(2,0)
);
   
CREATE UNIQUE INDEX "COUNTRIES_PK" ON "COUNTRIES" ("ID");
CREATE INDEX "COUNTRIES_NATIONALITY_IDX" ON "COUNTRIES" ("NATIONALITY"); 

ALTER TABLE "COUNTRIES" ADD CONSTRAINT "COUNTRIES_PK" PRIMARY KEY ("ID") USING INDEX "COUNTRIES_PK"  ENABLE;
ALTER TABLE "COUNTRIES" ADD CONSTRAINT "COUNTRIES_NATIONALITY_FK" FOREIGN KEY ("NATIONALITY") REFERENCES "NATIONALITY" ("COD") ENABLE;

COMMENT ON COLUMN "COUNTRIES"."ID" IS 'ID universal';
COMMENT ON COLUMN "COUNTRIES"."COD" IS 'Cod Pais de Origem';
COMMENT ON COLUMN "COUNTRIES"."DESCRIPTION" IS 'Nome do pais';
COMMENT ON COLUMN "COUNTRIES"."RAIS" IS 'Codigo do Pais de Origem';
COMMENT ON COLUMN "COUNTRIES"."CAGED" IS 'Codigo conforme manual do CAGED';
COMMENT ON COLUMN "COUNTRIES"."NATIONALITY" IS 'Codigo da Nacionalidade';
COMMENT ON TABLE  "COUNTRIES"  IS 'Unidades da Federação';

CREATE SEQUENCE COUNTRIES_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER COUNTRIES_ID_TRIGGER
BEFORE INSERT ON COUNTRIES
FOR EACH ROW
BEGIN
    :NEW.ID := COUNTRIES_SEQ.NEXTVAL;
END;


INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (13, 'AFEGANISTÃO', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (15, 'ALAND, ILHAS', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (17, 'ALBANIA, REPUBLICA DA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (23, 'ALEMANHA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (31, 'BURKINA FASO', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (37, 'ANDORRA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (40, 'ANGOLA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (41, 'ANGUILLA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (42, 'ANTÁRTICA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (43, 'ANTIGUA E BARBUDA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (53, 'ARABIA SAUDITA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (59, 'ARGELIA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (63, 'ARGENTINA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (64, 'ARMENIA, REPUBLICA DA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (65, 'ARUBA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (69, 'AUSTRALIA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (72, 'AUSTRIA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (73, 'AZERBAIJAO, REPUBLICA DO', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (77, 'BAHAMAS, ILHAS', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (80, 'BAHREIN, ILHAS', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (81, 'BANGLADESH', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (83, 'BARBADOS', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (85, 'BELARUS, REPUBLICA DA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (87, 'BELGICA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (88, 'BELIZE', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (90, 'BERMUDAS', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (93, 'MIANMAR (BIRMANIA)', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (97, 'BOLIVIA, ESTADO PLURINACIONAL DA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (98, 'BOSNIA-HERZEGOVINA (REPUBLICA DA)', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (99, 'BONAIRE, SAINT EUSTATIUS E SABA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (101, 'BOTSUANA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (102, 'BOUVET, ILHA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (105, 'BRASIL', NULL, NULL, 10);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (108, 'BRUNEI', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (111, 'BULGARIA, REPUBLICA DA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (115, 'BURUNDI', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (119, 'BUTAO', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (127, 'CABO VERDE, REPUBLICA DE', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (137, 'CAYMAN, ILHAS', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (141, 'CAMBOJA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (145, 'CAMAROES', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (149, 'CANADA', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (153, 'CAZAQUISTAO, REPUBLICA DO', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (154, 'CATAR', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (158, 'CHILE', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (160, 'CHINA, REPUBLICA POPULAR', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (161, 'FORMOSA (TAIWAN)', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (163, 'CHIPRE', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (165, 'COCOS(KEELING),ILHAS', NULL, NULL, NULL);
INSERT INTO COUNTRIES (COD, DESCRIPTION, RAIS, CAGED, NATIONALITY) VALUES (169, 'COLOMBIA', NULL, NULL, NULL);

COMMIT;
