CREATE TABLE "NATIONALITY" (
    "ID" NUMBER(18,0) NOT NULL ENABLE, 
    "COD" NUMBER(2,0), 
	"DESCRIPTION" VARCHAR2(60 BYTE), 
	"RAIS" NUMBER(2,0) NOT NULL ENABLE
)
CREATE UNIQUE INDEX "NATIONALITY_PK" ON "NATIONALITY" ("ID");
ALTER TABLE "NATIONALITY" ADD CONSTRAINT "NATIONALITY_PK" PRIMARY KEY ("ID") USING INDEX "NATIONALITY_PK"  ENABLE;

COMMENT ON COLUMN "NATIONALITY"."ID" IS 'Universal ID';
COMMENT ON COLUMN "NATIONALITY"."COD" IS 'Country of Origin Code';
COMMENT ON COLUMN "NATIONALITY"."DESCRIPTION" IS 'Country name';
COMMENT ON COLUMN "NATIONALITY"."RAIS" IS 'Cod rais country of origin';
