CREATE TABLE "STREET" (	
    "ID" NUMBER(18,0) NOT NULL ENABLE,
    "CITY" NUMBER(8,0) NOT NULL ENABLE, 
	  "STREET" NUMBER(8,0) NOT NULL ENABLE, 
	  "DESCRIPTION" VARCHAR2(150 BYTE), 
	  "TYPE" NUMBER(3,0) NOT NULL ENABLE
);

CREATE UNIQUE INDEX "STREET_PK" ON "STREET" ("ID");
CREATE INDEX "STREET_CITY_IDX" ON "STREET" ("CITY"); 

ALTER TABLE "STREET" ADD CONSTRAINT "STREET_PK" PRIMARY KEY ("ID") USING INDEX "STREET_PK"  ENABLE;
ALTER TABLE "STREET" ADD CONSTRAINT "STREET_CITY_FK" FOREIGN KEY ("CITY") REFERENCES "CITIES" ("COD") ENABLE

COMMENT ON COLUMN "STREET"."ID" IS 'ID universal';
COMMENT ON COLUMN "STREET"."CITY" IS 'City code';
COMMENT ON COLUMN "STREET"."STREET" IS 'Street​name';
COMMENT ON COLUMN "STREET"."DESCRIPTION" IS 'Street description';
COMMENT ON COLUMN "STREET"."TYPE" IS 'Type of street';
COMMENT ON TABLE  "STREET"  IS 'Streets';

CREATE SEQUENCE STREET_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER STREET_ID_TRIGGER
BEFORE INSERT ON STREET
FOR EACH ROW
BEGIN
    :NEW.ID := STREET_SEQ.NEXTVAL;
END;
