CREATE TABLE "USUARIOS_ROLES" (	
    "USUARIOS_UUID" NUMBER NOT NULL ENABLE, 
	"ROLE_UUID" NUMBER NOT NULL ENABLE
);

CREATE INDEX "USUARIO_UUID_IDX" ON "USUARIOS_ROLES" ("USUARIOS_UUID");
CREATE INDEX "ROLE_UUID_IDX" ON "ADMIN"."USUARIOS_ROLES" ("ROLE_UUID");

ALTER TABLE "USUARIOS_ROLES" ADD CONSTRAINT "SUARIO_ROLE_PK" PRIMARY KEY ("USUARIOS_UUID", "ROLE_UUID");
ALTER TABLE "USUARIOS_ROLES" ADD CONSTRAINT "USUARIO_FK" FOREIGN KEY ("USUARIOS_UUID") REFERENCES "USUARIOS" ("UUID") ON DELETE CASCADE ENABLE;
ALTER TABLE "USUARIOS_ROLES" ADD CONSTRAINT "ROLES_FK" FOREIGN KEY ("ROLE_UUID") REFERENCES "ROLES" ("UUID") ON DELETE CASCADE ENABLE;

INSERT INTO USUARIOS_ROLES (USUARIOS_UUID, ROLE_UUID) VALUES (1, 1);
INSERT INTO USUARIOS_ROLES (USUARIOS_UUID, ROLE_UUID) VALUES (1, 2);
COMMIT;
